### PR TITLE
IMc_denoise and Steinbock integration

### PR DESCRIPTION
**Pull request by BenCaiello**
Here is the integration I came up with to allow IMC_denoise to easily work with the data structures generated by steinbock.

I have not made a pull request before, so there may be some things missing / extra comments that are not really needed? Let me know if there is anything else I ought to do when creating one of these!

Importantly, my edits only are intended to work with the python / jupyter notebook aspects of the package and I have no idea how they affect / do not affect the rest of the package. 
I also have only used / tested my changes with my data in the multi-channel tiff data structure, and have not ever used it with the default, single-channel data structure.

I hope this ends up being helpful!

### CODE REVIEW

**Comment by BenCaiello** [comment]
Since I saw that Github tracks changes automatically (I'm new to this), I deleted my comments about where I had made changes to simplify  things.

Part of what I had originally placed in the README file to indicate the changes I had made I copy here for your reference:

_These edits are intended to allow the simple integration of IMC_denoise with the data structures produced by the steinbock package: https://github.com/BodenmillerGroup/steinbock. Specifically, the edits allow the uptake of multi-channel .tiffs by IMC_denoise in a distinct file structure (all .tiffs in one folder, no sub-folders).

Changes:

--> edited the DeepSNiF_DataGenerator.py file (in the IMC_denoise\DeepSNiF_utils folder)

      - modified file so that the package can ingest multi-channel .tiff data

      - This was only designed to be accessible through a python / Jupyter notebook script -- I am uncertain of how this would be integrated with the docker portion of IMC_denoise
      
      - This functionality is optionally set as part of the DeepSNiF Data Generator class
      
      - The original single-channel .tiff format should remain the default behavior (multi-channel must be explicitly defined to get the new behaviour)
      
--> added IMC_Denoise_integrated_with_steinbock_output.ipynb file to scripts folder

      - this is an example jupyter notebook script for how to use the new functionality
      
      - the example requires your directories (training, img, and output) to be manually set_

**Comment by BenCaiello** [comment]
Hello @PENGLU-WashU  ,

I had a question about the license on this repository -- reading over it, it seems to imply that I am likely not allowed to modify the package (or even "distribute" it to third parties which runs oddly a-foul of github's rules about forking...) -- I should be more careful reading these things as I go! 
I'm not sure if the code is technically yours as author or WashU's given the license's wording -- but I'm happy to abide by the license terms with this, although of course I do hope my edits can stay up / be incorporated in the package! Let me know what I/we ought to do with my edited version, I presume you know the process and rules better than me.

Also, have you had an opportunity to look at the changes I made? Hopefully with Lukas potentially testing it, it can be incorporated into the project and be useful for all the people using steinbock for IMC data!

**Comment by PENGLU-WashU** [comment]
> Hello @PENGLU-WashU  ,
> 
> 
> 
> I had a question about the license on this repository -- reading over it, it seems to imply that I am likely not allowed to modify the package (or even "distribute" it to third parties which runs oddly a-foul of github's rules about forking...) -- I should be more careful reading these things as I go! 
> 
> I'm not sure if the code is technically yours as author or WashU's given the license's wording -- but I'm happy to abide by the license terms with this, although of course I do hope my edits can stay up / be incorporated in the package! Let me know what I/we ought to do with my edited version, I presume you know the process and rules better than me.
> 
> 
> 
> Also, have you had an opportunity to look at the changes I made? Hopefully with Lukas potentially testing it, it can be incorporated into the project and be useful for all the people using steinbock for IMC data!

Hi,

Thank you both for the work! The code is under WashU license. However, I think it should be fine for you to modify or use without commercial usage.

I will read thoroughly on this code this weekend. I am so grateful of both of your work and discussions.BTW, after I approve the PR, could you please also modify the readme file regarding the usage of your code? I will definitely add you as a contributor of this project.

Please let me know if you have any questions.

**Review by PENGLU-WashU — APPROVED** [review]
Thanks for the contribution. Only a few suggestions:

1. Make sure the algorithm names are accurate with cases: DIMR and DeepSNiF.
2. Please also modify the readme file if you could.

**Comment by BenCaiello** [comment]
OK, Thanks! I've done a readme section for the new multichannel option and some other edits like the algorithm names and opened a new pull request for those changes.

**Pull request merged**
