### PR TITLE
Support for keras 3

### PR DESCRIPTION
**Pull request by g-torr**
Tested on keras 3.4  and tensorflow 2.17

### CODE REVIEW

**Review by PENGLU-WashU — COMMENTED** [review]
I see that the code can work on keras 3. However, for keras 2, can it still work?

**Comment by g-torr** [comment]
I tested on keras 2.3 and it works
Keras                  2.3.1
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.2
protobuf               3.20.3
tensorboard            2.2.2
tensorboard-plugin-wit 1.8.1
tensorflow             2.2.0
tensorflow-estimator   2.2.0

**Comment by PENGLU-WashU** [comment]
> I tested on keras 2.3 and it works Keras 2.3.1 Keras-Applications 1.0.8 Keras-Preprocessing 1.1.2 protobuf 3.20.3 tensorboard 2.2.2 tensorboard-plugin-wit 1.8.1 tensorflow 2.2.0 tensorflow-estimator 2.2.0

Thanks for the test! I have not found any issues on your code. I will test it on my machine and then approve your PR.

**Review by PENGLU-WashU — APPROVED** [review]

**Comment by PENGLU-WashU** [comment]
> I tested on keras 2.3 and it works Keras 2.3.1 Keras-Applications 1.0.8 Keras-Preprocessing 1.1.2 protobuf 3.20.3 tensorboard 2.2.2 tensorboard-plugin-wit 1.8.1 tensorflow 2.2.0 tensorflow-estimator 2.2.0

Hi, I have merged your PR. Thanks for your contribution! I have added an acknowledgement in the readme file to highlight your contribution to this project.

**Comment by g-torr** [comment]
Thank you very much!! I appreciate that

**Pull request merged**
